name: "Latest Version"
description: "Checks and outputs the latest version of the specified repo."
inputs:
  repo:
    description: "The repo that needs to be watched."
    required: true
  refer: # deprecated
    deprecationMessage: "Now we use cache to store reports, `refer` is no longer needed."
  out: # deprecated
    deprecationMessage: "In order to be used by cache, `out` is set to be mandatory."
  out_dir: # deprecated
    deprecationMessage: "For simplicity, `out_dir` will always be `./.latest-version/`."
outputs:
  is_update:
    description: "Are the any update for the tracked repo?"
  stable_ver:
    description: "The latest stable version of the tracked repo."
  result:
    description: "The Result, a report of the latest version information of the repo being watched."
  docker_tags:
    description: "The `tags` information that can be used by `docker/metadata-action` action."
runs:
  using: node20
  main: ./src/main.js
branding:
  icon: "hash"
  color: "blue"
